#!/bin/bash

# Absolute path of this file
BASEDIR=$(dirname $0)

if [ -f $BASEDIR/database.db ]; then
    rm $BASEDIR/database.db
fi

echo "Building database..."
echo "Building tables..."
cat $BASEDIR/sql/tables.sql | sqlite3 $BASEDIR/database.db

echo ""
echo "Database initialized successfully."
